/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunbooksRouteImport } from './routes/runbooks'
import { Route as OncallRouteImport } from './routes/oncall'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ApiAgentsChatRouteImport } from './routes/api/agents/chat'
import { Route as AgentsRunsRunIdRouteImport } from './routes/agents/runs/$runId'

const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksRoute = RunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const OncallRoute = OncallRouteImport.update({
  id: '/oncall',
  path: '/oncall',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsChatRoute = ApiAgentsChatRouteImport.update({
  id: '/api/agents/chat',
  path: '/api/agents/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRunsRunIdRoute = AgentsRunsRunIdRouteImport.update({
  id: '/agents/runs/$runId',
  path: '/agents/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/lineage': typeof LineageRoute
  '/oncall': typeof OncallRoute
  '/runbooks': typeof RunbooksRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/runs/$runId': typeof AgentsRunsRunIdRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/lineage': typeof LineageRoute
  '/oncall': typeof OncallRoute
  '/runbooks': typeof RunbooksRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/runs/$runId': typeof AgentsRunsRunIdRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/lineage': typeof LineageRoute
  '/oncall': typeof OncallRoute
  '/runbooks': typeof RunbooksRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/runs/$runId': typeof AgentsRunsRunIdRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidents'
    | '/lineage'
    | '/oncall'
    | '/runbooks'
    | '/settings'
    | '/telemetry'
    | '/agents/'
    | '/agents/runs/$runId'
    | '/api/agents/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidents'
    | '/lineage'
    | '/oncall'
    | '/runbooks'
    | '/settings'
    | '/telemetry'
    | '/agents'
    | '/agents/runs/$runId'
    | '/api/agents/chat'
  id:
    | '__root__'
    | '/'
    | '/incidents'
    | '/lineage'
    | '/oncall'
    | '/runbooks'
    | '/settings'
    | '/telemetry'
    | '/agents/'
    | '/agents/runs/$runId'
    | '/api/agents/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsRoute: typeof IncidentsRoute
  LineageRoute: typeof LineageRoute
  OncallRoute: typeof OncallRoute
  RunbooksRoute: typeof RunbooksRoute
  SettingsRoute: typeof SettingsRoute
  TelemetryRoute: typeof TelemetryRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsRunsRunIdRoute: typeof AgentsRunsRunIdRoute
  ApiAgentsChatRoute: typeof ApiAgentsChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks': {
      id: '/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof RunbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oncall': {
      id: '/oncall'
      path: '/oncall'
      fullPath: '/oncall'
      preLoaderRoute: typeof OncallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/chat': {
      id: '/api/agents/chat'
      path: '/api/agents/chat'
      fullPath: '/api/agents/chat'
      preLoaderRoute: typeof ApiAgentsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/runs/$runId': {
      id: '/agents/runs/$runId'
      path: '/agents/runs/$runId'
      fullPath: '/agents/runs/$runId'
      preLoaderRoute: typeof AgentsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsRoute: IncidentsRoute,
  LineageRoute: LineageRoute,
  OncallRoute: OncallRoute,
  RunbooksRoute: RunbooksRoute,
  SettingsRoute: SettingsRoute,
  TelemetryRoute: TelemetryRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsRunsRunIdRoute: AgentsRunsRunIdRoute,
  ApiAgentsChatRoute: ApiAgentsChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
