import type { Database } from "../db/client";
import { usageEvents } from "../db/schema";
import type { UsageRecord, UsageWriter } from "../ports/usage-writer";

/**
 * Drizzle/postgres usage writer. Inserts one row per record (id/createdAt are
 * generated by the DB). Errors are logged and swallowed — usage metering is
 * best-effort and must never fail the originating chat request.
 */
export function createPostgresUsageWriter(db: Database): UsageWriter {
  return {
    async write(record: UsageRecord): Promise<void> {
      try {
        await db.insert(usageEvents).values({
          tenant: record.tenant,
          promptTokens: record.promptTokens,
          completionTokens: record.completionTokens,
          model: record.model,
        });
      } catch (err) {
        const reason = err instanceof Error ? err.message : String(err);
        console.error("[gateway] usage write failed:", reason);
      }
    },
    async close() {
      // postgres.js connection lifecycle is owned by the process; nothing to do.
    },
  };
}
