#!/usr/bin/env bash
# Rebuild the kubernetes-mixin dashboards + recording rules for this lab.
#
# Self-dockerizing: run it from anywhere (Git Bash / WSL / CI) and it
# re-executes itself inside golang:1.24 - jb and jsonnet are pure-Go, so the
# container is the whole toolchain. Rerun after editing mixin.libsonnet or to
# bump the mixin (delete vendor/ + jsonnetfile.lock.json first for a bump).
#
# Outputs (committed - Grafana provisions the JSON, the Mimir ruler loads the
# rules; neither knows jsonnet exists):
#   ../provisioning/dashboards/k8s-mixin-*.json      (5 compute-resources + apiserver)
#   ../../mimir/rules/anonymous/k8s-mixin-recording.yaml
set -euo pipefail

if [ ! -f /.dockerenv ]; then
  # Repo root = three levels up from this script. cygpath + MSYS_NO_PATHCONV
  # keep Git Bash from rewriting the container-side paths into C:\... ones.
  root="$(cd "$(dirname "$0")/../../.." && pwd)"
  root="$(cygpath -m "$root" 2>/dev/null || echo "$root")"
  exec env MSYS_NO_PATHCONV=1 docker run --rm -v "$root:/repo" -w /repo/infra/grafana/mixins golang:1.24 ./build.sh
fi

export GOFLAGS=-mod=mod
go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest >/dev/null
go install github.com/google/go-jsonnet/cmd/jsonnet@latest >/dev/null
export PATH="$PATH:$(go env GOPATH)/bin"

[ -f jsonnetfile.json ] || jb init
[ -d vendor/kubernetes-mixin ] || jb install github.com/kubernetes-monitoring/kubernetes-mixin@master

# The dashboards this lab provisions: compute-resources drilldown chain +
# apiserver. The rest of the mixin (node/proxy/scheduler/windows/network)
# assumes exporters this cluster deliberately does not run.
WANT='["k8s-resources-cluster.json","k8s-resources-namespace.json","k8s-resources-pod.json","k8s-resources-workload.json","k8s-resources-workloads-namespace.json","apiserver.json"]'

mkdir -p out
jsonnet -J vendor --multi out -e "
  local m = import 'mixin.libsonnet';
  { [k]: m.grafanaDashboards[k] for k in ${WANT} }
" >/dev/null

for f in out/*.json; do
  # Provisioned files all share one flat folder; prefix so they sort together.
  mv "$f" "../provisioning/dashboards/k8s-mixin-$(basename "$f")"
done
rmdir out

# Recording rules only (the lab's cause-ALERTS are curated by hand in
# Grafana with 60-120s timing - the mixin's 10-15m alerts stay out). Groups
# whose rules read node-exporter metrics would only record empty series on
# this cluster; prune them.
{
  echo '# GENERATED by infra/grafana/mixins/build.sh - do not edit.'
  echo '# kubernetes-mixin recording rules (job selectors aligned to the'
  echo '# k8s-monitoring chart). The Mimir ruler stays record-only: every'
  echo '# firing alert in this lab lives in Grafana provisioning instead.'
  jsonnet -J vendor -S -e "
    local m = import 'mixin.libsonnet';
    local keep = ['k8s.rules', 'kube-apiserver-availability.rules', 'kube-apiserver-burnrate.rules', 'kubelet.rules'];
    std.manifestYamlDoc({
      groups: [
        g for g in m.prometheusRules.groups
        if std.length(std.filter(function(k) std.startsWith(g.name, k), keep)) > 0
      ],
    }, quote_keys=false)
  "
} > ../../mimir/rules/anonymous/k8s-mixin-recording.yaml

echo "wrote:"
ls -la ../provisioning/dashboards/k8s-mixin-*.json
echo "      ../../mimir/rules/anonymous/k8s-mixin-recording.yaml"
