import type { ChatResponse } from "@obs/contracts";

/** A single successful-inference record (id/createdAt generated by the DB). */
export interface InferenceRecord {
  readonly runId: string;
  readonly tenant: string;
  readonly model: string;
  readonly promptChars: number;
  readonly promptTokens: number;
  readonly completionTokens: number;
  readonly retrievedCount: number;
  readonly retrievalScoreMean: number | null;
  readonly retrievalScoreMax: number | null;
  readonly cacheHit: boolean;
  readonly status: "ok";
  readonly response: ChatResponse;
}

/**
 * Port: persists per-inference records to the `inferences` table for downstream
 * data-quality checks. Like the usage writer this is best-effort — a write
 * failure must never fail the originating chat, so `record` swallows its errors.
 */
export interface InferenceRecorder {
  record(record: InferenceRecord): Promise<void>;
  close(): Promise<void>;
}
